apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: gcloud-cleanup-orphaned-disks-qa
  namespace: ops
spec:
  schedule: "0 8 * * 2,4"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccount: gcloud-cleanup-orphaned-disks
          containers:
          - name: gcloud-cleanup-orphaned-disks-qa
            image: us.gcr.io/tvg-network/ops/gcloud-cleanup-orphaned-disks:IMAGE_TAG
            env:
              - name: ENV
                value: qa
              - name: PROJECT
                value: tvg-network
            args:
              - --slack-token 
              - 'SLACK_CREDENTIALS_VALUE'
              - --channel 
              - 'SLACK_CHANNEL_ID_VALUE'
              - --project 
              - $(PROJECT)
          restartPolicy: Never

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gcloud-cleanup-orphaned-disks
  namespace: ops